### PR TITLE
Add network_not_metered and custom check scripts

### LINKED ISSUE #115: Metered network connections are not respected
The updater should probably not run when only a metered network connection is available.

Otherwise, we might download multiple gigabytes of data when on a mobile connection with a limited mobile data plan and silently consume all of said data plan (this is what happened to me) or lead to very high bills (especially when considering 
roaming) without even giving the user any indication of this. For the reason of "unexpectedly high bills" I would consider this pretty high priority from an usability perspective.

The conventional way to check for metered connections would be to check [the `Metered` property](https://networkmanager.dev/docs/api/latest/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.Metered) of the `org.freedesktop.NetworkManager` D-Bus interface, which reports the current network status. This is what e.g. the GNOME Software Center claims to be doing in its settings dialog - except that we override that download mechanism in Bluefin, leading to it not respect metered connections despite saying so.

### PR DESCRIPTION
**Pull request by cr7pt0gr4ph7**
This pull request contains four small-ish fixes/improvements:

* Improve the documentation clarity in the main README.md
* Allow specifying lowercase log levels via `UBLUE_LOG` to match the behavior of most other tools
* Cleanup the config file loading logic, and avoid crashes when not all config options are specified.
* Add a `--config` CLI option to allow alternate config files when testing

...as well as two new features related to the update precondition checks (these two were the main driver for this pull request):

* Add a `network_not_metered` check to prevent downloading multiple GB of data when on metered/mobile connections
(the latter of which happened to me while using my smartphone as a hotspot).
This check should probably be enabled in all environments where NetworkManager is supported, to avoid annoying surprises on mobile data plans. It is currently disabled by default, though, to not break any existing installations.

* Add a facility for using fully custom scripts to check for additional preconditions.
My personal rationale for this is that I want to be able to prevent unnecessary background work when using my laptop for a DJ set, to avoid stutter. I'm not sure yet whether I want to use a manual settings toggle or automatic detection of the DJ software for this, but implementing it in a flexible manner allows me and other to solve these usecases without bloating up the `ublue_update` code too much.

Fixes #115

### CODE REVIEW

**Comment by cr7pt0gr4ph7** [comment]
Hi :wave: Just as a heads-up: Do you have any further questions about this PR? I'll be happy to answer them.

**Comment by gerblesh** [comment]
thanks so much for the PR! And thanks for giving this project some much needed love. LGTM, looks like it needs some formatting changes though. Sorry for the late reply, I've been pretty busy lately

**Review by gerblesh — APPROVED** [review]

**Comment by gerblesh** [comment]
ok so formatting changes should probably work with just `black` but it looks like CI is kinda borkeda

**Review by KyleGospo — APPROVED** [review]

**Comment by cr7pt0gr4ph7** [comment]
> thanks so much for the PR! And thanks for giving this project some much needed love. LGTM, looks like it needs some formatting changes though. Sorry for the late reply, I've been pretty busy lately
You're welcome! This resolves one of the (actually very few) hiccups I've discovered after switching to Bluefin, so I'm happy to make a great idea like Bluefin just a tiny bit greater.

**Pull request merged**
