### PR TITLE
feat: run system updates as root, run user updates for each user

### PR DESCRIPTION
**Pull request by gerblesh**
solves: https://github.com/ublue-os/ublue-update/issues/5

What's done:
 - Initial work on running updates as different users, getting the users to run updates on
What needs to be done:
 - Editing the RPM spec
 - Editing the config shipped
 - Coordinating with downstream projects (Bazzite)
 - Documentation on the new changes
 - Document extra config bugs  (rpm-ostreed conflicting services)

### CODE REVIEW

**Review by akdev1l — APPROVED** [review]

**Comment by gerblesh** [comment]
Currently waiting on bazzite downstream to coordinate a PR before merging

**Comment by EyeCantCU** [comment]
Bazzite is good to go!: https://github.com/ublue-os/bazzite/pull/301

**Comment by gerblesh** [comment]
merge this PR with: https://github.com/ublue-os/bazzite/pull/301

**Comment by gerblesh** [comment]
still need to squash!

**Review by EyeCantCU — APPROVED** [review]

**Pull request merged**
